### ISSUE TITLE
Italian 

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/OpeningHoursPhoto#1]
Hi Bryce,

these are the words for Italian:
(abbreviations for weekdays are first 2 or 3 letters)
Monday Lunedì
Tuesday Martedì
Wednesday Mercoledì
Thursday Giovedì
Friday Venerdì
Saturday Sabato
Sunday Domenica
continued hours (no lunch break) orario continuato
closed chiuso
open aperto
winter invernale
summer estivo
opening hours orario
from dalle
to alle
hours ore

**Comment by bryceco** [comment]
Thanks! Added in 51ef5bed3e799a558f90794ace820d80833b2c7c
